import pandas as pd
import jinja2
import pdfkit
import os
import time

# --- Configuration ---
REPORTS_DIR = "reports"
# Path to wkhtmltopdf executable. If it's in PATH, this might not be needed.
# On some systems, you might need to provide the full path.
# Example for Linux: WKHTMLTOPDF_PATH = '/usr/bin/wkhtmltopdf'
# Example for Windows: WKHTMLTOPDF_PATH = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
# If None, pdfkit will try to find it in PATH.
WKHTMLTOPDF_PATH = None # Set this if pdfkit cannot find wkhtmltopdf

DEFAULT_REPORT_TEMPLATE_STR = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ report_title }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { margin-top: 30px; font-size: 0.8em; text-align: center; color: #777; }
    </style>
</head>
<body>
    <h1>{{ report_title }}</h1>
    <p>Generated on: {{ generation_date }}</p>

    {% if data_df is not none and not data_df.empty %}
        <table>
            <thead>
                <tr>
                    {% for col in data_df.columns %}
                        <th>{{ col }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for index, row in data_df.iterrows() %}
                    <tr>
                        {% for col in data_df.columns %}
                            <td>{{ row[col] }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No data available for this report.</p>
    {% endif %}

    <div class="footer">
        Report generated by Social Media Analysis Tool
    </div>
</body>
</html>
"""

def generate_pdf_report(data_df, report_title, output_filename="report.pdf", template_str=DEFAULT_REPORT_TEMPLATE_STR):
    """
    Generates a PDF report from a Pandas DataFrame using Jinja2 and PDFKit.

    Args:
        data_df (pd.DataFrame): The data to include in the report.
        report_title (str): The title of the report.
        output_filename (str): The filename for the output PDF (without directory).
        template_str (str): The HTML template string.

    Returns:
        str: Path to the generated PDF, or None if generation failed.
    """
    if not os.path.exists(REPORTS_DIR):
        os.makedirs(REPORTS_DIR)

    output_filepath = os.path.join(REPORTS_DIR, output_filename)

    try:
        # Prepare template environment
        # template_loader = jinja2.FileSystemLoader(searchpath="./templates/") # If using external files
        # For embedded template string:
        env = jinja2.Environment(loader=jinja2.BaseLoader())
        template = env.from_string(template_str)

        generation_date = time.strftime("%Y-%m-%d %H:%M:%S")

        # Render HTML
        html_content = template.render(
            report_title=report_title,
            data_df=data_df,
            generation_date=generation_date
        )

        # Configure PDFKit options if wkhtmltopdf path is set
        config = None
        if WKHTMLTOPDF_PATH:
            try:
                config = pdfkit.configuration(wkhtmltopdf=WKHTMLTOPDF_PATH)
                print(f"Using wkhtmltopdf from: {WKHTMLTOPDF_PATH}")
            except Exception as e: # Catch if there's an issue with the configuration itself
                print(f"Warning: Could not configure wkhtmltopdf path '{WKHTMLTOPDF_PATH}': {e}. Will try system PATH.")

        # Generate PDF
        pdfkit.from_string(html_content, output_filepath, configuration=config, options={'enable-local-file-access': None})
        print(f"PDF report generated successfully: {output_filepath}")
        return output_filepath
    except FileNotFoundError as e:
        # This specific exception often means wkhtmltopdf is not installed or not in PATH
        print(f"ERROR: wkhtmltopdf not found. Please install it and ensure it's in your system's PATH.")
        print(f"Details: {e}")
        print("You can download it from: https://wkhtmltopdf.org/downloads.html")
        print("If installed, you might need to set WKHTMLTOPDF_PATH in this script.")
        return None
    except Exception as e:
        print(f"Error generating PDF report: {e}")
        return None

def generate_html_report(data_df, report_title, output_filename="report.html", template_str=DEFAULT_REPORT_TEMPLATE_STR):
    """
    Generates an HTML report from a Pandas DataFrame using Jinja2.

    Args:
        data_df (pd.DataFrame): The data to include in the report.
        report_title (str): The title of the report.
        output_filename (str): The filename for the output HTML (without directory).
        template_str (str): The HTML template string.

    Returns:
        str: Path to the generated HTML file, or None if generation failed.
    """
    if not os.path.exists(REPORTS_DIR):
        os.makedirs(REPORTS_DIR)

    output_filepath = os.path.join(REPORTS_DIR, output_filename)

    try:
        env = jinja2.Environment(loader=jinja2.BaseLoader()) # Using BaseLoader for string templates
        template = env.from_string(template_str)
        generation_date = time.strftime("%Y-%m-%d %H:%M:%S")

        html_content = template.render(
            report_title=report_title,
            data_df=data_df,
            generation_date=generation_date
        )

        with open(output_filepath, "w", encoding="utf-8") as f:
            f.write(html_content)

        print(f"HTML report generated successfully: {output_filepath}")
        return output_filepath
    except Exception as e:
        print(f"Error generating HTML report: {e}")
        return None


if __name__ == "__main__":
    print("Testing Report Generator...")

    # Create sample data
    sample_data = {
        'ID': [1, 2, 3, 4],
        'Platform': ['Twitter', 'Facebook', 'Twitter', 'Facebook'],
        'User': ['userA', 'userB', 'userC', 'userD'],
        'Text': [
            'This is a sample tweet for the report.',
            'Another interesting post from Facebook.',
            'Important update regarding the situation.',
            'A final piece of data for our PDF.'
        ],
        'Sentiment': ['Positive', 'Neutral', 'Negative', 'Positive'],
        'Topic': ['General News', 'Community Update', 'Crisis Alert', 'General News']
    }
    sample_df = pd.DataFrame(sample_data)

    report_title_pdf = "Sample PDF Report"
    pdf_file = generate_pdf_report(sample_df, report_title_pdf, "sample_report.pdf")
    if pdf_file:
        print(f"PDF generated: {pdf_file}")
    else:
        print("PDF generation failed. Check logs above, especially for wkhtmltopdf issues.")

    report_title_html = "Sample HTML Report"
    html_file = generate_html_report(sample_df, report_title_html, "sample_report.html")
    if html_file:
        print(f"HTML generated: {html_file}")
    else:
        print("HTML generation failed.")

    # Test with empty DataFrame
    empty_df = pd.DataFrame()
    title_empty_pdf = "Empty Data PDF Report"
    pdf_empty_file = generate_pdf_report(empty_df, title_empty_pdf, "empty_report.pdf")
    if pdf_empty_file:
        print(f"Empty PDF generated: {pdf_empty_file}")
    else:
        print("Empty PDF generation failed.")

    print("Report generator testing finished.")
